import pandas as pd

"""
This script creates a column called `publisher_group`,
where, depending on the `publisher` value it will assign
the name of the parent publisher company, either one of
'The Big 5' (Penguin Random House, Hachette, Macmillan,
Simon & Schuster, or HarperCollins), big independent
publishing company (Scholastic, Bloomsbury, etc.),
Comic/Manga publishing group (DC, Disney [Marvel], Viz Media,
etc.), University Press (Harvard University Press, Oxford
University Press, etc.), or 'indie' if none of the previous
applies (like micro-publishers, or self-published books).
This column will be used later for analysis of the publishers
and publishing groups with dominance in the New York Times
Bestseller list.
"""

# Load dataset
df = pd.read_csv('nyt_bestsellers_author_clean_publishers_FULL.csv')

# Big 5 Publishing Groups
PENGUIN_RANDOM_HOUSE = [
    "ACE",
    "ANCHOR",
    "AVERY",
    "BALLANTINE",
    "BANTAM",
    "BERKLEY",
    "BLUE RIDER PRESS",
    "BOOKS ON TAPE",
    "BROADWAY",
    "CELEBRA",
    "CLARKSON POTTER",
    "CONVERGENT",
    "COUNTRYMAN PRESS",
    "CROWN",
    "CURRENCY",
    "CURRENT",
    "CYGNET",
    "DAW",
    "DEL REY",
    "DELACORTE",
    "DELTA",
    "DIAL",
    "DK",
    "DOUBLEDAY",
    "DRAGONFLY",
    "DUTTON",
    "EMBER",
    "EVERYMAN'S LIBRARY",
    "FAMILY TREE",
    "FIREBIRD",
    "FREDERICK WARNE",
    "GOLDEN",
    "GOTHAM",
    "GRAPHIA",
    "GROSSET & DUNLAP",
    "HARMONY",
    "HOGARTH",
    "HUDSON STREET",
    "IMAGE",
    "IMPACT",
    "INTERMIX",
    "JOVE",
    "KATHY DAWSON",
    "KNOPF",
    "KOKILA",
    "KRAUSE",
    "LORENA JONES",
    "LOVESWEPT",
    "LUCASBOOKS",
    "MARINER",
    "MENTOR",
    "MICHAEL JOSEPH",
    "MODERN LIBRARY",
    "MULTNOMAH",
    "NAN A TALESE",
    "NANCY PAULSEN",
    "NEW AMERICAN LIBRARY",
    "NORTH LIGHT",
    "NOW I'M READING!",
    "ONE WORLD",
    "OBSIDIAN",
    "PAMELA DORMAN",
    "PANTHEON",
    "PENGUIN PRESS",
    "PENGUIN",
    "PENGUIN CLASSICS",
    "PENGUIN WORKSHOP",
    "PENGUIN AUDIO",
    "PENGUIN LIFE",
    "PENGUIN TEEN",
    "PENGUIN YOUNG READERS",
    "PERIGREE",
    "PHILOMEL",
    "PLUME",
    "PORTFOLIO",
    "POTTER CRAFT",
    "POTTER STUDIO",
    "POTTER STYLE",
    "PUFFIN",
    "PUTNAM",
    "RANDOM HOUSE CHILDREN'S BOOKS",
    "RANDOM HOUSE",
    "RANDOM HOUSE AUDIO",
    "RAZORBILL",
    "RIVERHEAD",
    "ROBIN COREY BOOKS",
    "ROC",
    "RODALE",
    "SCHOCKEN",
    "SCHWARTZ & WADE",
    "SENTINEL",
    "SHAYE AREHEART",
    "SIGNET",
    "SIGNETTE",
    "SJP",
    "SPEAK",
    "SPECTRA",
    "SPIEGEL & GRAU",
    "STEPPING STONE",
    "SYLVAN LEARNING",
    "TARCHERPERIGEE",
    "TEN SPEED",
    "THREE RIVERS PRESS",
    "TIM DUGGAN",
    "VIKING",
    "VILLARD",
    "VINTAGE",
    "WATERBROOK",
    "WATSON-GUPTILL",
    "WENDY LAMB",
    "WRITER'S DIGEST",
    "YEARLING BOOKS",
    "YEARLING",
    'ARCHAIA',
    'DELL',
    'HAY HOUSE',
]
MACMILLAN = [
  "CELADON",
  "DISTRIBUTED PUBLISHERS",
  "FARRAR, STRAUS & GIROUX",
  "FEIWEL & FRIENDS",
  "FIRST SECOND",
  "FLATIRON",
  "FORGE",
  "FSG ORIGINALS",
  "FSG BOOKS FOR YOUNG READERS",
  "GUINNESS"
  "HENRY HOLT",
  "HILL AND WANG",
  "HOLT BOOKS FOR YOUNG READERS",
  "IMPRINT",
  "KINGFISHER",
  "MACMILLAN AUDIO",
  "MACMILLAN CHILDREN'S PUBLISHING GROUP",
  "METROPOLITAN",
  "MICHAEL DI CAPUA",
  "MINOTAUR",
  "NEON SQUID",
  "ODD DOT",
  "PALGRAVE MACMILLAN",
  "PAN MACMILLAN",
  "PICADOR",
  "PRIDDY BOOKS",
  "QUICK AND DIRTY TIPS",
  "ROARING BROOK",
  "SARAH CRICHTON",
  "SQUARE FISH",
  "ST MARTIN'S GRIFFIN",
  "ST MARTIN'S",
  "STARSCAPE",
  "SWOON READS",
  "THOMAS DUNNE BOOKS",
  "TOR TEEN",
  "TOR",
  "TORDOTCOM",
  "TOR NIGHTFIRE",
  "YOUNG LISTENERS",
]
SIMON_AND_SCHUSTER = [
  "ADAMS MEDIA",
  "ALADDIN",
  "ARCHIE COMICS",
  "ARCHWAY",
  "ATHENEUM",
  "ATRIA",
  "AVID READER",
  "BEACH LANE",
  "CASTLE BOOKS",
  "DENENE MILLNER",
  "EMILY BESTLER BOOKS",
  "ENLIVEN",
  "FIRESIDE"
  "FOLGER SHAKESPEARE LIBRARY",
  "FREE PRESS",
  "GALLERY",
  "HOWARD",
  "JESSICA KINGSLEY",
  "JETER PUBLISHING",
  "LITTLE SIMON",
  "MARGARET K MCELDERRY",
  "ONE SIGNAL",
  "PAULA WISEMAN BOOKS",
  "PIMSLEUR",
  "POCKET BOOKS",
  "PRESIDIO",
  "SAGA",
  "SALAAM READS",
  "SCOUT PRESS",
  "SCRIBNER",
  "SIMON & SCHUSTER AUDIO",
  "SIMON & SCHUSTER BOOKS FOR YOUNG READERS",
  "SIMON & SCHUSTER",
  "SIMON PULSE",
  "SIMON SPOTLIGHT",
  "SIMON ACUMEN",
  "SIMON ELEMENT",
  "STREBOR BOOKS",
  "THRESHOLD EDITIONS",
  "TILLER PRESS",
  "TOUCHSTONE",
  "WASHINGTON SQUARE",
]
HACHETTE = [
  "AMACOM",
  "AVALON TRAVEL",
  "BACK BAY",
  "BASIC BOOKS",
  "BEAST BOOKS",
  "BLACK DOG & LEVENTHAL",
  "BOLD TYPE",
  "CENTER STREET",
  "CHRISTY OTTAVIANO",
  "DA CAPO PRESS",
  "ECONOMIST BOOKS",
  "FAITHWORDS",
  "FOREVER YOURS",
  "FOREVER",
  "GRAND CENTRAL",
  "HACHETTE AUDIO",
  "HACHETTE",
  "HACHETTE GO",
  "HACHETTE NASHVILLE",
  "HODDER & STOUGHTON",
  "JERICHO BOOKS",
  "JIMMY PATTERSON",
  "LB KIDS",
  "LEGACY LIT",
  "LITTLE, BROWN BOOKS FOR YOUNG READERS",
  "LITTLE, BROWN SPARK",
  "LITTLE, BROWN",
  "MOON TRAVEL",
  "MULHOLLAND BOOKS",
  "MYSTERIOUS",
  "ORBIT",
  "PERSEUS",
  "POPPY",
  "PUBLICAFFAIRS",
  "REAGAN ARTHUR",
  "REDHOOK",
  "RICK STEVES",
  "RUNNING PRESS",
  "SEAL PRESS",
  "SPRINGBOARD",
  "TWELVE",
  "VORACIOUS",
  "WATTPAD",
  "WELLNESS CENTRAL",
  "WORTHY",
  "YEN PRESS",
  'ALGONQUIN',
  'ALGONQUIN YOUNG READERS',
  'ARTISAN',
  'BUSINESS PLUS',
]
HARPERCOLLINS = [
  "AMISTAD",
  "ANTHONY BOURDAIN",
  "AVON",
  "B&H BOOKS",
  "BALZER + BRAY",
  "BIBLE GATEWAY",
  "BROADSIDE BOOKS",
  "CAEDMON",
  "CARINA PRESS",
  "CHOSEN BOOKS",
  "CLARION",
  "CUSTOM HOUSE",
  "DEY STREET BOOKS",
  "ECCO",
  "EDITORIAL VIDA",
  "EOS",
  "FAITHGATEWAY",
  "GRAPHIA",
  "GRAYDON HOUSE BOOKS",
  "GREENWILLOW",
  "GRUPO NELSON",
  "HANOVER SQUARE",
  "HARLEQUIN BOOKS",
  "HARLEQUIN TEEN",
  "HARLEQUIN AUDIO",
  "HARPER BUSINESS",
  "HARPER CELEBRATE",
  "HARPER DESIGN",
  "HARPER ELEMENT",
  "HARPER FESTIVAL",
  "HARPER LUXE",
  "HARPER PAPERBACKS",
  "HARPER PERENNIAL",
  "HARPER VOYAGER",
  "HARPER WAVE",
  "HARPER HORIZON",
  "HARPER INFLUENCE",
  "HARPER",
  "HARPERELIXIR",
  "HARPERALLEY",
  "HARPERAUDIO",
  "HARPERCHILDREN'S AUDIO",
  "HARPERCOLLINS 360",
  "HARPERCOLLINS CHILDREN'S BOOKS",
  "HARPERCOLLINS",
  "HARPERCOLLINS LEADERSHIP",
  "HARPERFESTIVAL",
  "HARPERONE",
  "HARPERSTUDIO",
  "HARPERTEEN",
  "HARPERVIA",
  "HEARTDRUM",
  "INKYARD",
  "IT BOOKS",
  "KATHERINE TEGEN",
  "KIMANI",
  "LOVE INSPIRED",
  "MARINER",
  "MICHAEL DI CAPUA",
  "MIRA BOOKS",
  "NELSON BOOKS",
  "NEW HARVEST",
  "OLIVE TREE",
  "PARK ROW",
  "QUILL TREE",
  "SANDPIPER",
  "SILHOUETTE",
  "SILOAM",
  "STEEPLE HILL",
  "THOMAS NELSON",
  "TOMMY NELSON",
  "W PUBLISHING GROUP",
  "WALDEN POND PRESS",
  "WESTBOW PRESS",
  "WESTINSTER PRESS",
  "WILLIAM MORROW",
  "WITNESS IMPULSE",
  "ZONDERKIDZ",
  "ZONDERVAN",
  'BOWEN PRESS',
  'COLLINS BUSINESS',
  'COLLINS DESIGN',
  'COLLINS LIVING',
  'COLLINS',
  'GERINGER',
  'HOUGHTON MIFFLIN HARCOURT',
]
# Independent publishers, not part of "The Big 5":
ABRAMS = ["ABRAMS BOOKS", "AMULET", "IMAGE",
          "COMICARTS","APPLESEED"]
BLOOMSBURY = ["BLOOMSBURY", "WALKER",
              "CONTINUUM"]
CHRONICLE = ["CHRONICLE"]
GROVE_ATLANTIC = ["GROVE",
                  "ATLANTIC MONTHLY PRESS",
                  "EL LEÓN LITERARY ARTS"]
KENSINGTON_PUBLISHING = ["KENSINGTON",
                         "BRAVA",
                         "CITADEL",
                         "DAFINA",
                         "ONYX",
                         "PINNACLE",
                         "ZEBRA",
                         "KENSINGTON COZIES"]
QUARTO_BOOKS = ["MBI PUBLISHING",
                "WELDON OWEN"]
QUIRK = ["QUIRK BOOKS"]
SKYHORSE = ["SKYHORSE",
            "SKY PONY PRESS",
            "SPORTS PUBLISHING",
            "ARCADE"]
SOURCEBOOKS = ["SOURCEBOOKS", "JABBERWOCKY",
               "LANDMARK", "CASABLANCA","FIRE",
               "WONDERLAND", "EXPLORE"]
WW_NORTON = ["W W NORTON & CO"]
WORKMAN = ["WORKMAN PUBLISHING"]
SCHOLASTIC = ["SCHOLASTIC",
              "ARTHUR A LEVINE",
              "CHICKEN HOUSE",
              "GRAPHIX",
              "KLUTZ",
              "ORCHARD",
              "KOALA",
              "MARGARET HAMILTON",
              "OMNIBUS",
              "9 STORY MEDIA",
              "POINT",
              "CARTWHEEL"]

# Comics, manga, and entertainment
DARK_HORSE = ["DARK HORSE",
              "DARK HORSE BOOKS",
              "DARK HORSE MANGA",
              "DARK HORSE COMICS"]
WARNER = ["DC COMICS",
          "VERTIGO",
          "WILDSTORM",
          "DC BLACK LABEL",
          "DC INK"]
DISNEY = ["HYPERION",
          "KINGSWELL",
          "MARVEL",
          "DISNEY",
          "DISNEY MANGA",
          "RICK RIORDAN PRESENTS"]
IDW = ["IDW"]
IMAGE = ["IMAGE COMICS"]
ONI = ["ONI PRESS"]
TOP_SHELF = ["TOP SHELF PRODUCTIONS"]
VIZ_MEDIA = ["VIZ MEDIA"]
KODANSHA = ["VERTICAL", "KODANSHA"]

# Universities
UNIVERSITY_PRESS = ['OXFORD UNIVERSITY PRESS', 'HARVARD UNIVERSITY PRESS',
       'PRINCETON UNIVERSITY PRESS', 'UNIVERSITY OF CALIFORNIA',
       'COLUMBIA UNIVERSITY PRESS', 'YALE UNIVERSITY PRESS',
       'UNIVERSITY OF CHICAGO PRESS',
       'UNIVERSITY OF NORTH CAROLINA PRESS',
       'UNIVERSITY PRESS OF MISSISSIPPI', 'UNIVERSITY OF MICHIGAN PRESS',
       'UNIVERSITY OF NEBRASKA PRESS', 'VANDERBILT UNIVERSITY PRESS',
       'TRINITY UNIVERSITY', 'UNIVERSITY OF NEW MEXICO PRESS',
       'UNIVERSITY OF IOWA PRESS']

# Dictionary with all of the groups
PUBLISHER_GROUPS = {
    "PENGUIN RANDOM HOUSE": PENGUIN_RANDOM_HOUSE,
    "MACMILLAN": MACMILLAN,
    "HACHETTE": HACHETTE,
    "HARPERCOLLINS": HARPERCOLLINS,
    "SIMON & SCHUSTER": SIMON_AND_SCHUSTER,

    # Independent
    "ABRAMS": ABRAMS,
    "BLOOMSBURY": BLOOMSBURY,
    "CHRONICLE": CHRONICLE,
    "GROVE ATLANTIC": GROVE_ATLANTIC,
    "KENSINGTON PUBLISHING": KENSINGTON_PUBLISHING,
    "QUARTO BOOKS": QUARTO_BOOKS,
    "QUIRK": QUIRK,
    "SKYHORSE": SKYHORSE,
    "SOURCEBOOKS": SOURCEBOOKS,
    "W W NORTON & CO": WW_NORTON,
    "WORKMAN PUBLISHING": WORKMAN,
    "SCHOLASTIC": SCHOLASTIC,

    # Comics
    "DARK HORSE": DARK_HORSE,
    "WARNER": WARNER,
    "DISNEY": DISNEY,
    "IDW": IDW,
    "IMAGE": IMAGE,
    "ONI": ONI,
    "TOP SHELF": TOP_SHELF,
    "VIZ MEDIA": VIZ_MEDIA,

    # Other
    "UNIVERSITY PRESS": UNIVERSITY_PRESS
}

# Create a reverse dictionary for later mapping
publisher_to_parent = {}

for parent, imprints in PUBLISHER_GROUPS.items():
    for imprint in imprints:
        publisher_to_parent[imprint] = parent

# Mapping the groups into the `publishing_group` column
df['publishing_group'] = (
    df['publisher']
    .map(publisher_to_parent)
    .fillna('OTHER')
)
df.to_csv('nyt_bestsellers_final.csv',index=False)